name: Terraform Destroy [lambda api dynamodb]
 
on:
  workflow_dispatch:
 
env:
  AWS_REGION: "us-east-1"
  TF_VERSION: "1.10.0"
 
jobs:
  terraform_lambda_api_dynamo_destroy:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
 
      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
 
      # Initialize Terraform
      - name: Terraform Init
        run: |
          cd infra
          terraform init
 
      # Validate Terraform configuration
      - name: Terraform Validate
        run: |
          cd infra
          terraform validate
 
      # Run Terraform Destroy
      - name: Terraform Destroy
        run: |
          cd infra
          terraform destroy -var-file="terraform.tfvars" -auto-approve
